### ISSUE TITLE
VS problem - bug or feature?

### ISSUE THREAD

**Issue by jsbien** [FrankMittelbach/fmitex-unicodefonttable#5] opened 2022-10-16 07:57 UTC
unicodefonttable is affected by the problem described by me at the XeTeX list (https://tug.org/pipermail/xetex/2022-October/028101.html); unfortunately I got (yet?) no comments.
fntsample prints the VS1 glyph from the font in question without any problem. The minimal example attached to my XeTeX list post doesn't work neither in XeLaTeX nor in LuaLaTeX.

**Comment by FrankMittelbach** [comment] 2022-10-16 11:59
I couldn't find any sample code involving unicodefonttable in the post you mentioned. However, if I understand it correctly the VS1 is not a printable glyph but a codepoint to alter other glyphs. There may be a few fonts that have a printable symbol in that slot and clearly emacs is using one of them but the noto font you used in your post obviously doesn't.

Unicodefonttable simply tables all glyphs in the font by attempting to typeset one after another. if a slot doesn't yield to a printable result then nothing is shown. so in that sense I would say it works as designed.

One could perhaps add a table to the unicodefonttable code which it looks up if "something" is in a font slot but doesn't yield to a printable glyph. However, in all honesty, I doubt that I will have the bandwidth to extend the package in that direction in the forseeable future.

**Comment by jsbien** [comment] 2022-10-16 13:00
>  the noto font you used in your post obviously doesn't.

Why do you think so? I proved it has the glyph by enclosing the output of fntsample:
[VS1sample.pdf](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9795061/VS1sample.pdf)

>  it looks up if "something" is in a font slot but doesn't yield to a printable glyph. 

I don't think fntsample is doing anything so strange. 

I suspect a bug in XeTeX/LuaTeX core. It is easier for you to draw the attention of the developers :-)

\documentclass{standalone}
\usepackage{fontspec}
\setmainfont{Noto Sans Manichaean}
\begin{document}
\thispagestyle{empty}

\char"10AC5

\char"10AC5 ︀

\char"10AC5\char"FE00

︀

\char"FE00

^^^^fe00

\end{document}

[VS1.pdf](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9795071/VS1.pdf)
[VS1lua.pdf](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9795072/VS1lua.pdf)
`

**Comment by FrankMittelbach** [comment] 2022-10-16 16:21
I checked. In Unicode this slot is `default-ignorable` and both XeTeX and LuaTeX do not print glyphs with that attribute (probably because the aren't not meant for printing).

In luaTeX (but not in XeTeX I think) you can change this behavior, e.g.
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Script=Arabic,RawFeature={-invisible}]{Noto Sans Manichaean}
\begin{document}
\thispagestyle{empty}

\char"10AC5

\char"10AC5 ︀

\char"10AC5\char"FE00

︀

\char"FE00

^^^^fe00
\end{document}
```
but do ask me further, because this is not my area of expertise.

Anyway, it is not an issue with unicodefonttable but a behavior of the engines, so I'm going to close this issue.

**Closed as completed by FrankMittelbach** 2022-10-16 16:21 UTC
Labels: works as designed

**Comment by jsbien** [comment] 2022-10-16 16:35
Thank you very much for finding the explanation!
