### ISSUE TITLE
Lack of clear, even the shortest, documentation how to use this package

### ISSUE THREAD

**Issue by Mariusz-W** [FrankMittelbach/fmitex-unicodefonttable#4] opened 2022-09-28 09:09 UTC
I apologize for posting this as an issue. This package, that I installed via MiKTeX, has no instruction how to use it. What is in the TUGboat article is not helpful. None of the supplied sources I am able to compile. In spite of having 35 years of experience with TeX/LaTeX/pdfTex/XeLaTeX I wasn’t able to figure out how to make this package do what it is supposed to do.

**Comment by jsbien** [comment] 2022-09-28 11:09
The subject of the issue is rather an overstatement, but I confirm it is close to impossible to run the sample sources out of the box, primarily because the fonts used are not easily available. I was able to use the package, but by trial and error, the documentation is not clear also for me.
[JSBtest.zip](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9664252/JSBtest.zip)
BTW, GitHub allows now providing the discussion tab in the repository.

**Comment by FrankMittelbach** [comment] 2022-09-28 16:20
I'm sure documentation can always be improved but I'm somewhat surprised by both statements.

- the package comes with documentation (or should if correctly distributed), so something like `texdoc unicodefonttable` should produce the documentation.

Now that documentation is more or less the TUB article, but I fail to see why it is difficult to follow or use.

- Ok it does not state that the package has to be loaded (but I would a expect that is obvious).
- It does not state explicitly that the font names as used in the examples assume lualatex is used. It only states that the font name used in \displayfonttable has to follow the fontspec conventions and they are different for the two engines XeTeX and LuaTeX (if fonts are used that are not system fonts). That is perhaps an oversight and could be improved, but it is stated in the documentation (in a roundabout way)
-  Other than that just copying the lines from the example section should work, e.g.

```
\documentclass{article}

\usepackage{unicodefonttable}

\begin{document}

\displayfonttable*[color=none, range-end=7F]{cmss10}

\displayfonttable*[color=none]{lmmi10} 
\displayfonttable*[color=none]{lmsy10} 
\displayfonttable*[color=none]{lmex10}

\displayfonttable[hex-digits=head+foot, range-end=1FFFF,
compare-with=New Computer Modern Math, 
title-format=\caption{Latin Modern Math compared to New Computer Modern Math}, 
title-format-cont=\caption{LM Math vs.\ NewCM Math, \emph{cont.}}, 
compare-color=black, 
compare-bgcolor=black!5, 
missing-glyph-color=black!50, color=black!75] 
{Latin Modern Math}

\displayfonttable[range-start=1D000, range-end=1D0FF,
hex-digits=block, missing-glyph-color=black!50, color=black!75, 
statistics-format=Total number of glyphs in this block of #1 is #2] {Garamond Libre}
\end{document}
```

I also fail to see why it should be difficult to reprocess the documentation because all fonts used are part of TeXLive (at least if you install them.

**Comment by jsbien** [comment] 2022-09-28 17:00
I made intensive experiments about too week ago and I unfortunately don't remember the details besides the general impression that it was cumbersome and confusing. I will try to reproduce the problems and to report them here. I use Debian which splits TexLive into many packages and I install only those which I really need, but identifying the needed package is not always easy. 

> the package comes with documentation (or should if correctly distributed), so something like texdoc unicodefonttable should produce the documentation.

The package is not available in Debian stable (it will be in Debian testing), so I was using the version from the repository. I had to find with Google how to use dtx and ins files (I used them earlier, but about 10 years ago). The version from CTAN, on the other hand, does not provide, at least explicitly, the source of unicodefonttable-samples.pdf.

These were the first obstacles I encountered in my experiments.

**Comment by jsbien** [comment] 2022-09-28 17:16
> It does not state explicitly that the font names as used in the examples assume lualatex is used

I noticed lualatex mentioned but assumed that it is supposed to work also with XeLaTex, which seems to be true. I understand the font names are just OTF/TTF names and that's how they should be described.

**Comment by FrankMittelbach** [comment] 2022-09-28 21:15
> > It does not state explicitly that the font names as used in the examples assume lualatex is used
> 
> I noticed lualatex mentioned but assumed that it is supposed to work also with XeLaTex, which seems to be true. I understand the font names are just OTF/TTF names and that's how they should be described.

As I said this is an oversight and I should explicitly mention that at the start of the examples (which is why I keep the PR open) but it is implicitly said, because it is stated that the font names have to follow the fontspec naming convention and thoe are different for XeTeX and LuaTeX. LuaTeX finds fonts in the texmf tree if they are given with their font name but XeTeX only finds them if they are installed as system fonts. Fonts only available in the texmf tree need to be given as xxx.otf if you want to use them with XeTeX. That is something I assumed is known to people using those engines because it is discussed at length in the fontspec documentation (and which is implicitly in the statement the name must follow the fontspec conventions).

But as I said I think it would be helpful to say that as given the examples are meant for LuaLaTeX (because of the way the fonts are referred to).

Other then that it works perfectly with XeTeX (or upTeX or ....) all you need to do is to use the same way you specify a font in `\setmainfont`.

**Comment by FrankMittelbach** [comment] 2022-09-28 21:23
> I made intensive experiments about too week ago and I unfortunately don't remember the details besides the general impression that it was cumbersome and confusing. I will try to reproduce the problems and to report them here. I use Debian which splits TexLive into many packages and I install only those which I really need, but identifying the needed package is not always easy.
> 
> > the package comes with documentation (or should if correctly distributed), so something like texdoc unicodefonttable should produce the documentation.
> 
> The package is not available in Debian stable (it will be in Debian testing), so I was using the version from the repository. I had to find with Google how to use dtx and ins files (I used them earlier, but about 10 years ago). The version from CTAN, on the other hand, does not provide, at least explicitly, the source of unicodefonttable-samples.pdf.
> 
> These were the first obstacles I encountered in my experiments.

I'm sorry, but if you use Debian and Debian doesn't provide the package or provides it crippled then please report problems to the Debian maintainers. Installing from CTAN is possible but then you do indeed have to go through various steps that these days nearly nobody does (or has to). That is not explicitly documented as these days out of the millions of LaTeX users be 2 to 5 dozen people do it this way (and for all others documenting that would be more confusing than helpful).

However, if you go from the repository  you could use
```
l3build doc
l3build install
```
and it would produce the documentation for you and installs it in your local texmf tree (and no that is also not documented it is just the way all packages using l3build work)

**Comment by jsbien** [comment] 2022-09-29 07:45
>  LuaTeX finds fonts in the texmf tree if they are given with their font name but XeTeX only finds them if they are installed as system fonts. 

I use XeLaTeX for years and happened to use LuaLaTeX at least twice but was not aware of this difference, which probably was the culprit of most of my problems.

> it is discussed at length in the fontspec documentatione

Really? Please point the relevant fragments. I look up the fontspec documentation from time to time but never noticed it. BTW, not only myself consider the fontspec documentation quite confusing, cf.  https://github.com/psb1558/Junicode-font/discussions/145#discussioncomment-3538842.

**Comment by FrankMittelbach** [comment] 2022-09-29 09:35
The fontspec documentation is not easy I agree, but this is not so surprising given that the package is written over a longer period of time by several volunteers. 
Maybe you find the documentation in the new LaTeX Companion easier, maybe not.  (Coming out early next year)
Anyway, this doesn't belong here really. The section I was referring to is about fonts by name and fonts by file name.

**Comment by jsbien** [comment] 2022-09-29 09:46
Thanks! It was stupid of me to forget about this part of the documentation :-(

**Comment by jsbien** [comment] 2022-09-29 10:09
I had some problems with range-start and range-end, which I cannot now reproduce - probably they were the results of my typos or other mistakes. However the message "Total number of glyphs in..." is definitely wrong, the number reported is the number of glyphs printed.
BTW, I'm quite happy you handle all the planes as plane 15 is used in Junicode :-) Thank you!

**Comment by FrankMittelbach** [comment] 2022-11-12 13:58
"Total number of glyphs in ..."   has no been changed to "Total number of glyphs shown from ..." (coming in the next update), which is probably a better default, but as mentioned in the documentation, depending on the circumstances you might want a totally different text which you can provide via a key.

**Comment by FrankMittelbach** [comment] 2022-11-12 14:32
Added a note stating that all examples assume the use of luatex and that for xetex the font specification may need adjustment.

**Closed as completed by FrankMittelbach** 2022-11-12 14:32 UTC
Labels: documentation
